apiVersion: v1
kind: Service
metadata:
  name: mi325-vllm0246
  namespace: default
spec:
  selector:
    app: mi325-vllm0246
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30080
      protocol: TCP