apiVersion: v1
kind: Service
metadata:
  name: mi325-vllm1357
  namespace: default
spec:
  selector:
    app: mi325-vllm1357
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30081
      protocol: TCP