apiVersion: v1
kind: Service
metadata:
  name: mi350-vllm-latest
  namespace: default
spec:
  selector:
    app: mi350-vllm-latest
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
