apiVersion: v1
kind: Service
metadata:
  name: vllm-8000
  namespace: default
spec:
  selector:
    app: mi325-vllm01234567
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-8001
  namespace: default
spec:
  selector:
    app: mi325-vllm01234567
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8001
      nodePort: 30081
      protocol: TCP