apiVersion: v1
kind: Service
metadata:
  name: mi325-vllm-0111
  namespace: default
spec:
  selector:
    app: mi325-vllm-0111
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
